import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.sidikoff.com'

  const staticPages = [
    // Main pages (French default)
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/services`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/projects`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/tarifs`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/faq`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/mentions-legales`,
      lastModified: new Date(),
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
    // English pages
    {
      url: `${baseUrl}/en`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/en/services`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/en/projects`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/en/tarifs`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/en/faq`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/en/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/en/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    // Russian pages
    {
      url: `${baseUrl}/ru`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/ru/services`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/ru/projects`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/ru/tarifs`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/ru/faq`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/ru/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/ru/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    },
  ]

  // Generate SEO location pages
  const seoLocations = [
    // Paris Districts (1-20)
    'paris-1',
    'paris-2',
    'paris-3',
    'paris-4',
    'paris-5',
    'paris-6',
    'paris-7',
    'paris-8',
    'paris-9',
    'paris-10',
    'paris-11',
    'paris-12',
    'paris-13',
    'paris-14',
    'paris-15',
    'paris-16',
    'paris-17',
    'paris-18',
    'paris-19',
    'paris-20',
    // Lyon Districts (1-9)
    'lyon-1',
    'lyon-2',
    'lyon-3',
    'lyon-4',
    'lyon-5',
    'lyon-6',
    'lyon-7',
    'lyon-8',
    'lyon-9',
    // Major French Cities
    'marseille',
    'toulouse',
    'nice',
    'nantes',
    'lille',
    'rennes',
    'reims',
    'saint-etienne',
    'toulon',
    'grenoble',
    'dijon',
    'angers',
    'villeurbanne',
    'le-mans',
    'aix-en-provence',
    'clermont-ferrand',
    'brest',
    'tours',
    'amiens',
    'limoges',
    'annecy',
    'boulogne-billancourt',
    'perpignan',
    'besancon',
    'metz',
    'mulhouse',
    'caen',
    'nancy',
    'argenteuil',
    'montreuil',
    'roubaix',
    'tourcoing',
    'nanterre',
    'avignon',
    'poitiers',
    'fort-de-france',
    'courbevoie',
    'versailles',
    'colombes',
    'aulnay-sous-bois',
    'saint-paul',
    'rueil-malmaison',
    'champigny-sur-marne',
    'antibes',
    'dunkerque',
    'pessac',
    'levallois-perret',
    'noisy-le-grand',
    'cergy',
    'pau',
    'ivry-sur-seine',
    'creteil',
    'orleans',
    'bourges',
    'cannes',
    'le-havre',
    'montrouge',
    'neuilly-sur-seine',
    'sarcelles',
    'troyes',
    'issy-les-moulineaux',
    'montauban',
    'lorient',
    'beauvais',
    'cholet',
    'vannes',
    'laval',
    'charleville-mezieres',
    'allonnes',
    'valence',
    'les-abymes',
    'quimper',
    'meaux',
    'biarritz',
    'auxerre',
    'la-rochelle',
    'matoury',
    'evry-courcouronnes',
    'calais',
    'merignac',
    'saint-malo',
    'chelles',
    'bourg-en-bresse',
    'blois',
    'cagnes-sur-mer',
    'salon-de-provence',
    'saint-brieuc',
    'saint-nazaire',
    'chatou',
    'garges-les-gonesse',
    'savigny-sur-orge',
    'pontoise',
    'sens',
    'evreux',
    'choisy-le-roi',
    'suresnes',
    'puteaux',
    'clichy',
    'saint-germain-en-laye',
    'franconville',
    'drancy',
    'gagny',
    'livry-gargan',
    'sevran',
    'vitry-sur-seine',
    'thiais',
    'fresnes',
    'fontenay-sous-bois',
    'noisy-le-sec',
    'maisons-alfort',
    'saint-maur-des-fosses',
    'vincennes',
    'nogent-sur-marne',
    'le-perreux-sur-marne',
    'bry-sur-marne',
    'joinville-le-pont',
    'saint-mande',
    'charenton-le-pont',
    'alfortville',
    'maisons-laffitte',
    'le-vesinet',
    'sartrouville',
    'houilles',
    'carrieres-sur-seine',
    'le-port-marly',
    'marnes-la-coquette',
    'vaucresson',
    'chaville',
    'sevres',
    'vanves',
    'malakoff',
    'bagneux',
    'fontenay-aux-roses',
    'le-plessis-robinson',
    'chatenay-malabry',
    'antony',
    'bourg-la-reine',
    'sceaux',
    'rungis',
    'chevilly-larue',
    'l-hay-les-roses',
    'cachan',
    'arcueil',
    'gentilly',
    'le-kremlin-bicetre',
    'villejuif',
    'saint-maurice',
    'bagnolet',
    'les-lilas',
    'le-pre-saint-gervais',
    'pantin',
    'bobigny',
    'bondy',
    'rosny-sous-bois',
    'villemomble',
    'montfermeil',
    'clichy-sous-bois',
    'coubron',
    'vaujours',
    'le-blanc-mesnil',
    'dugny',
    'le-bourget',
    'la-courneuve',
    'stains',
    'pierrefitte-sur-seine',
    'villetaneuse',
    'epinay-sur-seine',
    'saint-denis',
    'l-ile-saint-denis',
    'saint-ouen-sur-seine',
    'garches',
    'saint-cloud',
    'meudon',
    'clamart',
    // French Regions
    'ile-de-france',
    'auvergne-rhone-alpes',
    'hauts-de-france',
    'nouvelle-aquitaine',
    'occitanie',
    'grand-est',
    'provence-alpes-cote-d-azur',
    'pays-de-la-loire',
    'bretagne',
    'normandie',
    'bourgogne-franche-comte',
    'centre-val-de-loire',
    'corse',
    'guadeloupe',
    'martinique',
    'guyane',
    'la-reunion',
    'mayotte',
  ]

  const seoPages = seoLocations.flatMap((slug) => [
    // French version (default)
    {
      url: `${baseUrl}/seo/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    // English version
    {
      url: `${baseUrl}/en/seo/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    // Russian version
    {
      url: `${baseUrl}/ru/seo/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
  ])

  return [...staticPages, ...seoPages]
}
