// Main page sections - optimized for tree shaking
export { Hero } from './Hero'
export { default as About } from './About'
export { Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as Pricing } from './Pricing'
export { default as Testimonials } from './Testimonials'
export { FAQ } from './FAQ'
export { default as Contact } from './Contact'
export { Actualite } from './Actualite'
export { SeoAuditTool } from './SeoAuditTool'

// Yandex 360 Ecosystem Redesign Sections
export { Yandex360Hero } from './Yandex360Hero'
export { Yandex360Ecosystem } from './Yandex360Ecosystem'
export { Yandex360Bento } from './Yandex360Bento'
export { Yandex360Calculator } from './Yandex360Calculator'
export { Yandex360Portfolio } from './Yandex360Portfolio'
export { Yandex360Testimonials } from './Yandex360Testimonials'
export { Yandex360FAQ } from './Yandex360FAQ'
export { Yandex360Contact } from './Yandex360Contact'
